### ISSUE TITLE
Contingency won't accept max_retries=0

### ISSUE THREAD

**Issue by withtwoemms** [withtwoemms/recruitment#39]
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    __consumer = Consumer(Coordinator(Commlink(sqs_config), Contingency(max_retries=0)))
  File "~/recruitment/recruitment/agency/__init__.py", line 137, in __new__
    return cls.__call__(cls, *args, **kwargs)
TypeError: __call__() missing 1 required positional argument: 'action'
```

**Comment by withtwoemms** [comment]
this happens because there is a truthiness check in `Contingency`. making an exception for the int `0` should rectify.
